import type { TestReport, Failure, SuiteStats } from './parse-results';

export const LEGACY_MARKER = '<!-- prestaflow-report -->';

export function markerFor(projectKey: string): string {
  return projectKey === '' ? LEGACY_MARKER : `<!-- prestaflow-run:${projectKey} -->`;
}

// Backward-compat export — still consumed by pr-comment.ts until Task 3 replaces the finder.
export const MARKER = LEGACY_MARKER;

const MAX_FAILURES = 20;
const MAX_MESSAGE_LEN = 200;

export interface BuildBodyParams {
  report: TestReport;
  reportUrl: string;
  suites: string[];
  psVersion: string | null;
  sha: string;
  projectKey: string;
}

function formatDuration(ms: number): string {
  const s = Math.round(ms / 1000);
  if (s < 60) return `${s}s`;
  const m = Math.floor(s / 60);
  const r = s % 60;
  return `${m}m ${r.toString().padStart(2, '0')}s`;
}

function metaLine(suites: string[], psVersion: string | null): string {
  const parts: string[] = [];
  if (suites.length) parts.push(`Suites: ${suites.map(s => `\`${s}\``).join(', ')}`);
  if (psVersion) parts.push(`PS \`${psVersion}\``);
  return parts.join(' · ');
}

function footer(sha: string): string {
  const short = sha.slice(0, 7);
  return `<sub>Generated by [PrestaFlow/github-action@v2](https://github.com/PrestaFlow/github-action) · commit \`${short}\`</sub>`;
}

function truncateMessage(s: string): string {
  return s.length <= MAX_MESSAGE_LEN ? s : s.slice(0, MAX_MESSAGE_LEN) + '…';
}

function renderFailure(f: Failure): string {
  const loc = f.file ? `\n> \`${f.file}:${f.line}\`` : '';
  return `**❌ ${f.suite} / ${f.title}**\n> ${truncateMessage(f.message)}${loc}`;
}

function renderPerSuiteTable(suites: SuiteStats[]): string {
  if (suites.length <= 1) return '';
  const rows = suites.map(s =>
    `| ${s.name} | ${s.passed} | ${s.failed} | ${formatDuration(s.durationMs)} |`,
  );
  return [
    '| Suite | ✔ Passed | ✘ Failed | Duration |',
    '|-------|:--------:|:--------:|:--------:|',
    ...rows,
  ].join('\n');
}

function successBody(p: BuildBodyParams): string {
  const meta = metaLine(p.suites, p.psVersion);
  const perSuite = renderPerSuiteTable(p.report.suites);
  const lines = [
    markerFor(p.projectKey),
    `### PrestaFlow — Test report ✅`,
    ``,
    `**${p.report.total} tests passed in ${formatDuration(p.report.durationMs)}**`,
    ``,
  ];
  if (perSuite) { lines.push(perSuite, ``); }
  if (meta) { lines.push(meta, ``); }
  if (p.reportUrl) { lines.push(`📊 [View full report](${p.reportUrl})`, ``); }
  lines.push(footer(p.sha));
  return lines.join('\n');
}

function failureBody(p: BuildBodyParams): string {
  const shown = p.report.failures.slice(0, MAX_FAILURES);
  const extra = p.report.failures.length - shown.length;
  const details = shown.map(renderFailure).join('\n\n')
    + (extra > 0 ? `\n\n… +${extra} more failed. View full run for the complete list.` : '');
  const meta = metaLine(p.suites, p.psVersion);
  const perSuite = renderPerSuiteTable(p.report.suites);
  const lines = [
    markerFor(p.projectKey),
    `### PrestaFlow — Test report`,
    ``,
    `**Result: ❌ ${p.report.failed} failures out of ${p.report.total} tests**`,
    ``,
    `| Passed | Failed | Skipped | Duration |`,
    `|--------|--------|---------|----------|`,
    `| ${p.report.passed} ✅ | ${p.report.failed} ❌ | ${p.report.skipped} ⏭️ | ${formatDuration(p.report.durationMs)} |`,
    ``,
  ];
  if (perSuite) { lines.push(perSuite, ``); }
  if (meta) { lines.push(meta, ``); }
  lines.push(
    `<details>`,
    `<summary>Failure details (${p.report.failed})</summary>`,
    ``,
    details,
    ``,
    `</details>`,
    ``,
  );
  if (p.reportUrl) { lines.push(`📊 [View full report](${p.reportUrl})`, ``); }
  lines.push(footer(p.sha));
  return lines.join('\n');
}

export function buildCommentBody(p: BuildBodyParams): string {
  return p.report.failed === 0 ? successBody(p) : failureBody(p);
}
