import type { TestReport, Failure } from './parse-results';

export const MARKER = '<!-- prestaflow-report -->';

export interface BuildBodyParams {
  report: TestReport;
  reportUrl: string;
  suites: string[];
  psVersion: string | null;
  sha: string;
}

function formatDuration(ms: number): string {
  const s = Math.round(ms / 1000);
  if (s < 60) return `${s}s`;
  const m = Math.floor(s / 60);
  const r = s % 60;
  return `${m}m ${r.toString().padStart(2, '0')}s`;
}

function metaLine(suites: string[], psVersion: string | null): string {
  const parts: string[] = [];
  if (suites.length) parts.push(`Suites: ${suites.map(s => `\`${s}\``).join(', ')}`);
  if (psVersion) parts.push(`PS \`${psVersion}\``);
  return parts.join(' · ');
}

function footer(sha: string): string {
  const short = sha.slice(0, 7);
  return `<sub>Generated by [PrestaFlow/github-action@v2](https://github.com/PrestaFlow/github-action) · commit \`${short}\`</sub>`;
}

function renderFailure(f: Failure): string {
  const loc = f.file ? `\n> \`${f.file}:${f.line}\`` : '';
  return `**❌ ${f.suite} / ${f.title}**\n> ${f.message}${loc}`;
}

function successBody(p: BuildBodyParams): string {
  const meta = metaLine(p.suites, p.psVersion);
  const lines = [
    MARKER,
    `### PrestaFlow — Test report ✅`,
    ``,
    `**${p.report.total} tests passed in ${formatDuration(p.report.durationMs)}**`,
    ``,
  ];
  if (meta) { lines.push(meta, ``); }
  lines.push(`📊 [View full report](${p.reportUrl})`, ``, footer(p.sha));
  return lines.join('\n');
}

function failureBody(p: BuildBodyParams): string {
  const shown = p.report.failures.slice(0, 10);
  const extra = p.report.failures.length - shown.length;
  const details = shown.map(renderFailure).join('\n\n')
    + (extra > 0 ? `\n\n> …and ${extra} more — see full report.` : '');
  const meta = metaLine(p.suites, p.psVersion);
  const lines = [
    MARKER,
    `### PrestaFlow — Test report`,
    ``,
    `**Result: ❌ ${p.report.failed} failures out of ${p.report.total} tests**`,
    ``,
    `| Passed | Failed | Skipped | Duration |`,
    `|--------|--------|---------|----------|`,
    `| ${p.report.passed} ✅ | ${p.report.failed} ❌ | ${p.report.skipped} ⏭️ | ${formatDuration(p.report.durationMs)} |`,
    ``,
  ];
  if (meta) { lines.push(meta, ``); }
  lines.push(
    `<details>`,
    `<summary>Failure details (${p.report.failed})</summary>`,
    ``,
    details,
    ``,
    `</details>`,
    ``,
    `📊 [View full report](${p.reportUrl})`,
    ``,
    footer(p.sha),
  );
  return lines.join('\n');
}

export function buildCommentBody(p: BuildBodyParams): string {
  return p.report.failed === 0 ? successBody(p) : failureBody(p);
}
