name: "Upload to PrestaFlow"
description: "Uploads files to PrestaFlow via PrestaFlow API"
author: "PrestaFlow"
inputs:
  token:
    description: "Token used to authenticate with PrestaFlow API. Use a repository secret for this."
    required: true
  projectId:
    description: "Project id (numerical) to upload file to. You can get the numerical ID from the sidebar on a project page."
    required: false
  execute:
    description: "Execute the Composer action"
    required: false
    default: 'true'
outputs:
  id:
    description: "Output ID"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: 'layers'
  color: 'blue'
