import * as core from '@actions/core';
import * as fs from 'fs';
import * as path from 'path';

// Back-office credentials baked into the prestashop-flashlight image
// (see https://github.com/PrestaShop/prestashop-flashlight#readme).
export const FLASHLIGHT_BO_EMAIL = 'admin@prestashop.com';
export const FLASHLIGHT_BO_PASSWD = 'prestashop';
// Flashlight renames the admin folder to this fixed name.
export const FLASHLIGHT_ADMIN_DIR = 'admin-dev';

const KEY_RE = /^[A-Za-z_][A-Za-z0-9_.]*$/;

/**
 * Encode a value for phpdotenv (vlucas/phpdotenv ^5).
 *
 * Single quotes are fully literal in phpdotenv (no escapes, no `${VAR}`
 * interpolation, `#` is not a comment), which is what we want for URLs and
 * JSON (PRESTAFLOW_EXTRA_HEADERS, PRESTAFLOW_COOKIES). A single-quoted value
 * cannot contain `'` though, so those values (and multi-line ones) use double
 * quotes, where phpdotenv only accepts the escapes \" \\ \$ \n \r \t \f \v.
 */
export function encodeDotenvValue(value: string): string {
  if (!/['\r\n]/.test(value)) return `'${value}'`;
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\$/g, '\\$')
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n');
  return `"${escaped}"`;
}

export function pickPrestaflowEnv(env: NodeJS.ProcessEnv): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(env)) {
    if (k.startsWith('PRESTAFLOW_') && KEY_RE.test(k) && v !== undefined) out[k] = v;
  }
  return out;
}

function block(title: string, vars: Record<string, string>): string[] {
  const keys = Object.keys(vars);
  if (!keys.length) return [];
  return [`# ${title}`, ...keys.map(k => `${k}=${encodeDotenvValue(vars[k])}`), ''];
}

export interface RenderParams {
  foUrl: string;
  psVersion: string;
  /** Raw content of the user's dotenv file (.env.local or .env), if any. */
  userContent: string | null;
  /** PRESTAFLOW_* variables from the Action's process env (step `env:`). */
  processEnv: Record<string, string>;
}

export function flashlightDefaults(): Record<string, string> {
  return { PRESTAFLOW_BO_EMAIL: FLASHLIGHT_BO_EMAIL, PRESTAFLOW_BO_PASSWD: FLASHLIGHT_BO_PASSWD };
}

export function flashlightForced(foUrl: string, psVersion: string): Record<string, string> {
  return {
    PRESTAFLOW_FO_URL: foUrl,
    PRESTAFLOW_BO_URL: `${foUrl}${FLASHLIGHT_ADMIN_DIR}/`,
    PRESTAFLOW_PS_VERSION: psVersion,
  };
}

/**
 * Build the .env.local body. phpdotenv loads a single file (the first of
 * .env.local / .env that exists), and within that file a later assignment of
 * the same key overrides an earlier one. Layers are therefore written from the
 * lowest to the highest priority:
 *   Flashlight default credentials < user file < Flashlight URLs/version < step env.
 * The user file is copied verbatim so its own syntax (quotes, export, ${VAR})
 * is interpreted by phpdotenv itself.
 */
export function renderFlashlightDotenv(p: RenderParams): string {
  const lines: string[] = [
    '# Generated by PrestaFlow/github-action for the Flashlight run.',
    '# Later assignments win. The original file is restored after the run.',
    '',
    ...block('Flashlight default back-office credentials', flashlightDefaults()),
  ];
  if (p.userContent !== null) {
    lines.push('# --- user dotenv file ---', p.userContent.replace(/\s*$/, ''), '# --- end of user dotenv file ---', '');
  }
  lines.push(...block('Flashlight instance', flashlightForced(p.foUrl, p.psVersion)));
  lines.push(...block('Step environment (PRESTAFLOW_*)', p.processEnv));
  return lines.join('\n').replace(/\n*$/, '\n');
}

export interface WriteParams {
  workspace: string;
  foUrl: string;
  psVersion: string;
  processEnv: NodeJS.ProcessEnv;
}

export interface DotenvHandle {
  path: string;
  /** Keys written by the Action (they must not be inherited by the PHP process). */
  keys: string[];
  /** Put back the original .env.local (or remove the generated one). */
  restore: () => void;
}

export function writeFlashlightDotenv(p: WriteParams): DotenvHandle {
  const localPath = path.join(p.workspace, '.env.local');
  const envPath = path.join(p.workspace, '.env');
  const original = fs.existsSync(localPath) ? fs.readFileSync(localPath, 'utf-8') : null;
  // Mirror phpdotenv: when .env.local exists, .env is never read.
  let userContent = original;
  let userSource = '.env.local';
  if (userContent === null && fs.existsSync(envPath)) {
    userContent = fs.readFileSync(envPath, 'utf-8');
    userSource = '.env';
  }

  const processEnv = pickPrestaflowEnv(p.processEnv);
  const body = renderFlashlightDotenv({ foUrl: p.foUrl, psVersion: p.psVersion, userContent, processEnv });
  fs.writeFileSync(localPath, body);

  const keys = Array.from(new Set([
    ...Object.keys(flashlightDefaults()),
    ...Object.keys(flashlightForced(p.foUrl, p.psVersion)),
    ...Object.keys(processEnv),
  ]));
  if (original !== null) {
    core.info(`Existing .env.local merged into the generated one; it will be restored after the run.`);
  }
  core.info(
    `Wrote ${localPath} (Flashlight values${userContent !== null ? ` + ${userSource}` : ''}`
    + `${Object.keys(processEnv).length ? ` + ${Object.keys(processEnv).length} PRESTAFLOW_* from step env` : ''})`,
  );

  const restore = (): void => {
    try {
      if (original !== null) fs.writeFileSync(localPath, original);
      else fs.rmSync(localPath, { force: true });
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      core.warning(`Could not restore ${localPath}: ${msg}`);
    }
  };

  return { path: localPath, keys, restore };
}
